document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<title></title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<footer>");
document.writeln("		<div class=\'topbottom\'>");
document.writeln("			<div class=\'my\'>");
document.writeln("				<span>XXXX</span>");
document.writeln("				<ul>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("					<a href=\'\'>XXXX</a>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\'my_two\'>");
document.writeln("				<span>BBBBB</span>");
document.writeln("				<ul>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("					<a href=\'\'>MMMMMMM</a>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'albottom\'>");
document.writeln("			<div class=\'bottom_img\'>");
document.writeln("				<img src=\'./resource/img/6.png\'>");
document.writeln("				<img src=\'./resource/img/7.png\'>");
document.writeln("				<img src=\'./resource/img/8.png\'>");
document.writeln("			</div>");
document.writeln("			<div class=\'bottom_w\'>");
document.writeln("				<p>");
document.writeln("					<span>页尾位置</span>");
document.writeln("					<p>什么都没写什么都没写什么都没写什么都没写</p>");
document.writeln("					<span>什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写什么都没写</span>");
document.writeln("					<p>什么都没写什么都没写</p>");
document.writeln("				</p>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</footer>	");
document.writeln("</body>");
document.writeln("</html>");