document.writeln("<!--页眉-共通-->");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<title></title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<header>");
document.writeln("		<nav class=\'topnav\'>");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<a class=\'home\' href=\'./home.html\'>首页</a>");
document.writeln("				</li>	");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("					<a class=\'gameplay\' href=\'#gameplay\'>简单小游戏");
document.writeln("					</a>");
document.writeln("					<ul class=\'dropdown-game\'>");
document.writeln("      					<li><a class=\'saolei\' href=\'./saolei.html\'>扫雷</a></li>");
document.writeln("      					<li><a class=\'tanchishe\' href=\'#\'>贪吃蛇</a></li>");
document.writeln("    				</ul>");
document.writeln("    			</li>");
document.writeln("				<li class=\'rightnav\'>");
document.writeln("					<a class=\'morefun\' href=\'#morefun\'>更多</a>");
document.writeln("				</li>");
document.writeln("			</ul>				");
document.writeln("		</nav>");
document.writeln("	</header>");
document.writeln("</body>");
document.writeln("</html>");